- id: snyk-iac
  name: Snyk IaC Validation
  description: Snyk IaC Validation
  require_serial: true
  entry: hooks/snyk-precommit.sh
  language: script
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$